# frozen_string_literal: true

app_identifier("com.danfakkeldy.routey")
metadata_path(File.expand_path("fastlane/metadata", Dir.pwd))
screenshots_path(File.expand_path("fastlane/screenshots", Dir.pwd))

skip_binary_upload(true)
skip_screenshots(true)
submit_for_review(false)
force(true)

run_precheck_before_submit(false)
precheck_default_rule_level(:warn)
